#ifndef __DEFINEMACRO_H__
#define __DEFINEMACRO_H__

#define C_ID_WIDTH 6
#define C_NAME_WIDTH 8
#define C_PHONNUMBER_WIDTH 11
#define C_ADRESS_WIDTH 63
#define C_EMAIL_WIDTH 24

#define O_ID_WIDTH 6
#define O_CLIENTID_WIDTH 6
#define O_PRODUCTNAME_WIDTH 42
#define O_PRODUCTID_WIDTH 6
#define O_PRICE_WIDTH 16
#define O_STOCK_WIDTH 13


#define P_ID_WIDTH 6
#define P_NAME_WIDTH 39
#define P_BRAND_WIDTH 34
#define P_PRICE_WIDTH 17
#define P_STOCK_WIDTH 16


#endif